### ISSUE TITLE
How to train ScratchDet with mmdetection？

### ISSUE THREAD

**Issue by yanlongbinluck** [KimSoybean/ScratchDet#9]
thanks for your great repo.
I put **ssd300_scratchdet_coco.py** into folder of mmdetection/configs; 
  put **ssd_root34_300.py** into mmdetection/mmdet/model/backbones, 
  and  put **ssdbn_head.py** into mmdetection/mmdet/model/anchor_heads.

run **./tools/train.py configs/ssd300_scratchdet_coco.py**, there are some errors: **None is not in the backbone registry**.
is my method right? or I need to set some other parameters? 
thanks

**Comment by jshuzi** [comment]
@yanlongbinluck 
Have you find out how to train ScratchDet with mmdetection? Recently, i've been trying this too.

**Comment by jshuzi** [comment]
I have met the same error.

**Comment by zwh-l** [comment]
in the  ssd_root34_300.py, 'from ..registry import BACKBONES' and '@BACKBONES.register_module' are lost.

**Comment by jshuzi** [comment]
@zwh-l while i run the command ./tools/dist_train.sh configs/ssd300_scratchdet_coco.py 2 --validate, i got an error:
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jshuzi/mmcv/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/models/detectors/single_stage.py", line 60, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
TypeError: loss() got an unexpected keyword argument 'gt_bboxes_ignore'
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jshuzi/mmcv/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/jshuzi/mmdetection/mmdet/models/detectors/single_stage.py", line 60, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
TypeError: loss() got an unexpected keyword argument 'gt_bboxes_ignore'
Traceback (most recent call last):
  File "/home/jshuzi/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jshuzi/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/jshuzi/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/ssd300_scratchdet_coco.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
Have you met the problem? thank you for your reply.

**Comment by zwh-l** [comment]
@jshuzi It's about single_stage or two_stage, single_stage have no parameter of 'gt_bboxes_ignore'. mmdetection has updated codes to solve it. [https://github.com/open-mmlab/mmdetection/pull/327/commits/f1d06cdc70a81fbeee219f7c99654c319131ab8a](url)

**Comment by zwh-l** [comment]
@jshuzi single_stage have no parameter of gt_bboxes_ignore
and two_stage have it. in mmdetection , pull requests:Allow gt_bboxes_ignore for RPN and single-stage detectors can solve it.

**Comment by jshuzi** [comment]
@zwh-l sorry, i don't quite understand, which parts of the code should I modify?

**Comment by zwh-l** [comment]
@jshuzi    [https://github.com/open-mmlab/mmdetection/pull/327/files](url)

**Comment by zwh-l** [comment]
@jshuzi https://github.com/open-mmlab/mmdetection/pull/327/files

**Comment by jshuzi** [comment]
@zwh-l thank you very much. i have solved the above problem with your help. i use the ScratchDet to train my own data. But, i meet an new error, valueerror: expected input batch_size (8764) to match target batch_size (8732), have you met the error before?

**Comment by zwh-l** [comment]
@jshuzi , I met，but I can't solve it. So I gave up and run ssd512_scratchdet. It can work.
